name: Publish

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '3.1.100' ]
    name: DotNet Version ${{ matrix.dotnet }}
    steps:
      - uses: actions/checkout@v1
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}    
      
      - name: Build
        run: dotnet build --configuration Release

      - name: Unit Tests
        run: dotnet tes
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Nuget Pack
        run: dotnet pack --output nupkgs -c Release -p:PackageReleaseNotes="${{ github.sha }}"
      
      - name: Nuget Publish
        run: dotnet nuget push "nupkgs\*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
